- app/controllers/subdomains_controller.rb
- config/routes.rb
- spec/features/csrf_token_spec.rb
@mpawlik please check if it works for you. If yes I will merge it into `master`.
> CSRF token in json for js requests

- Gemfile
- Gemfile.lock
- app/controllers/apps_controller.rb
- app/models/app.rb
- spec/controllers/apps_controller_spec.rb
To make it simple friendly_id gem was used.
/cc @bwilk please take a look
> Subdomain used as app id

- app/controllers/subdomains_controller.rb
- config/routes.rb
- spec/features/info_spec.rb
Inside info JSON information about `csrfToken` and `userLogin` are available.
> Info rest API path

- app/assets/stylesheets/generic/timeline.scss
- app/views/apps/_activity.html.haml
- app/views/apps/activity.html.haml
Very basic timeline for activities. For sure additional styling is needed here. We should add info about: time, user login, different icons for different activity types.
> Basic activity timeline

- Gemfile
- Gemfile.lock
- config/initializers/raven.rb
To turn it on add `RAVEN_DSN` variable with raven dsn value.
> Sentry integration

- Gemfile
- Gemfile.lock
- app/controllers/jobs_controller.rb
- app/views/jobs/show.html.haml
- app/views/layouts/_navbar.html.haml
- config/locales/en.yml
- config/routes.rb
- db/migrate/20150319125019_add_admin_role_to_user.rb
- db/schema.rb
> Delayed jobs monitoring view for admin

- app/assets/stylesheets/sections/app.scss
- app/views/layouts/app/_footer.html.haml
- db/schema.rb
Remove dice specific information from app login page footer. 
@bwilk please take a look
> Remove dice specific elements from app footer

- app/assets/stylesheets/sections/deploy.scss
- app/views/deploys/_upload_types.html.haml
- config/locales/en.yml
- config/locales/pl.yml
> Better style for upload types

- app/assets/stylesheets/sections/deploy.scss
- app/views/apps/_app_tab.html.haml
- app/views/deploys/_upload_types.html.haml
- app/views/deploys/zip.html.haml
- config/locales/en.yml
- config/locales/pl.yml
- spec/features/user_pushes_to_production_spec.rb
> Dev app in header and push to production

- app/views/help/show.html.haml
- config/locales/en.yml
- config/locales/pl.yml
- doc/js_libs.en.md
- doc/js_libs.pl.md
> Stub for JS libs documentation

- app/controllers/help_controller.rb
- app/views/layouts/_navbar.html.haml
> Show help also for non logged in users

- app/views/layouts/_navbar.html.haml
- config/locales/en.yml
- config/locales/pl.yml
* use PlgApp as codename
* add active class for PlgApp when on `home` controller
> Plgapp section

- doc/js_libs.en.md
- doc/js_libs.pl.md
- public/plgapp/plgapp.js
Task-Url: https://jira.plgrid.pl/jira/browse/PLGAPP-15
> PLGAPP-15: magic in place and documented

- app/controllers/concerns/proxyable.rb
- app/controllers/datanet_controller.rb
- app/models/user.rb
- config/application.yml
- config/routes.rb
- db/schema.rb
- lib/proxy/datanet.rb
- lib/proxy/plgdata.rb
- lib/proxy/rimrock.rb
- spec/models/user_spec.rb
> Datanet proxy endpoint

- app/assets/stylesheets/generic/flash.scss
> Place flash above page content

- app/controllers/application_controller.rb
- spec/features/locales_spec.rb
> Reject invalid locale value from cookie

- app/controllers/concerns/proxyable.rb
> Add content type header only when set by proxy response

- app/controllers/application_controller.rb
> Check authorization before csrf

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.coffee
- app/controllers/apps_controller.rb
- app/helpers/application_helper.rb
- app/services/app_service.rb
- app/services/push_to_production_service.rb
- app/views/apps/_activity.html.haml
- app/views/deploys/_upload_types.html.haml
- config/locales/en.yml
- config/locales/pl.yml
- db/migrate/20150617122845_add_activity_message.rb
- db/schema.rb
- spec/features/app_activities_spec.rb
- spec/features/user_pushes_to_production_spec.rb
- spec/services/push_to_production_service_spec.rb
- vendor/assets/javascripts/jquery.timeago.js
User is able to pass push to production message, what is more activities view is extended: activity message and created at time is shown.
> Push to production message

- config/locales/errors.en.yml
- config/locales/errors.pl.yml
Error messages for file upload and mini magic processing error
> Set carrierwave error messages

- db/migrate/20150622192816_add_default_app_content_value.rb
- db/schema.rb
- lib/carrierwave/storage/app.rb
- spec/features/download_app_spec.rb
Add possibility to download application zip without any file.
> Download empty app

- app/controllers/datanet_controller.rb
- config/locales/errors.en.yml
- config/locales/errors.pl.yml
- spec/features/datanet_proxy_spec.rb
Only letters, digits and `-` are allowed.
> Validate datanet repository name

- misc/monitoring/plgapp_probe.py
This branch contains first and hopefully final version of nagios probe for plgapp.
> Plgapp nagios probe

- app/views/deploys/zip.html.haml
- config/locales/en.yml
- config/locales/pl.yml
- config/locales/simple_form.en.yml
- config/locales/simple_form.pl.yml
- spec/features/upload_app_spec.rb
> Add missing translations for members tab and zip upload

- app/services/dropbox/delete_service.rb
- app/services/dropbox/move_service.rb
- spec/services/dropbox/delete_service_spec.rb
> Reuse move service when renaming dir wile deleting app

- app/controllers/application_controller.rb
- app/mailers/app_mailer.rb
- app/models/user.rb
- db/migrate/20150725092422_add_user_locale.rb
- db/schema.rb
- spec/mailers/app_mailer_spec.rb
- spec/models/user_spec.rb
> Send email with locales selected by the user

- app/jobs/dropbox/push_job.rb
- app/services/dropbox/delete_service.rb
- config/locales/en.yml
- config/locales/pl.yml
- spec/jobs/dropbox/push_job_spec.rb
- spec/services/dropbox/delete_service_spec.rb
> Respect user locale while renaming dropbox directories
